name: Test - Xcode (default)
on:
  push:
    branches:
      - master
      - feature/**
      - fix/**
  pull_request:
    branches:
      - master
jobs:
  test_ios:
    name: Test framework
    runs-on: macOS-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@master
      - name: Prepare Tools
        run: |
          git lfs install --skip-smudge
          brew tap thii/xcbeautify https://github.com/thii/xcbeautify.git
          brew install swiftlint xcbeautify
          carthage update --platform ios,macos --no-use-binaries
      - name: Build and Test SPM
        run: |
          set -o pipefail && swift build -c debug
          echo "SKIPPING: \"set -o pipefail && swift test -Xlinker -LResources/macOS | xcbeautify\""
      - name: Test iOS target
        run: |
          set -o pipefail && xcodebuild clean test -project PactSwift.xcodeproj -scheme PactSwift-iOS -destination "platform=iOS Simulator,name=iPhone 11 Pro" | xcbeautify
      - name: Test macOS target
        run: |
          set -o pipefail && xcodebuild clean test -project PactSwift.xcodeproj -scheme PactSwift-macOS -destination "platform=macOS,arch=x86_64" | xcbeautify
      - name: Test it builds for Carthage
        run: |
          carthage build --no-skip-current
      - name: Trigger tests on examples repos
        run: |
          curl -XPOST -u "${{ secrets.PAT_USERNAME}}:${{secrets.PAT_TOKEN}}" -H "Accept: application/vnd.github.everest-preview+json"  -H "Content-Type: application/json" https://api.github.com/repos/surpher/pact-swift-examples/dispatches --data '{"event_type": "build_application"}'
