name: Test - Xcode (11.3.1)
on:
  push:
    branches:
      - master
      - feature/**
  pull_request:
    branches:
      - master
jobs:
  test_ios:
    name: Test iOS framework
    runs-on: macOS-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@master
      - name: Force Xcode 11.3.1
        run: sudo xcode-select -switch /Applications/Xcode_11.3.1.app
      - name: Prepare Tools
        run: |
          git lfs install --skip-smudge
          brew tap thii/xcbeautify https://github.com/thii/xcbeautify.git
          brew install swiftlint xcbeautify
          carthage update --platform ios --no-use-binaries --configuration Debug
      - name: Compile and Test - SPM
        run: |
          swift build -c debug
          swift build -c release
          swift test -Xlinker -LResources/lib | xcbeautify
      - name: Test project - iOS (Xcode)
        run: |
          set -o pipefail && xcodebuild clean test -project PactSwift.xcodeproj -scheme PactSwift -destination "platform=iOS Simulator,name=iPhone 11 Pro" | xcbeautify
      - name: Test it builds for Carthage
        run: |
          carthage build --no-skip-current
